### ISSUE TITLE
Where is ZegoAudioRoom plugin?

### ISSUE THREAD

**Issue by LunaGao** [zegoim/zego-flutter-sdk#1]
I only need to using audio in my app, but it's for zegoliveroom. I can't find any zegoaudioroom plugin for flutter.

Please add zegoaudioroom.

**Comment by qypengzai** [comment]
hello. ZegoLiveRoom SDK contains video and audio module, so you can only use its audio api in your app.

**Comment by qypengzai** [comment]
> I only need to using audio in my app, but it's for zegoliveroom. I can't find any zegoaudioroom plugin for flutter.
> 
> Please add zegoaudioroom.

hello. ZegoLiveRoom SDK contains video and audio module, so you can only use its audio api in your app.
