### ISSUE TITLE
Any plan for support androidx ?

### ISSUE THREAD

**Issue by LunaGao** [zegoim/zego-flutter-sdk#2]
I am using some flutter plugin which are already migrated to androidx, and it makes me migrated my code to androidx also. After then, zego flutter plugin built failed in my project. 
Is there a plan to migrated android sdk to androidx or how can I using flutter sdk when my project already migrated to androidx ?

refs: https://developer.android.com/jetpack/androidx/migrate

**Comment by zegodev** [comment]
Hello, zegoliveroomplugin 1.0.4 remove all android support because we don't need it. So you can upgrade sdk and try to build your project again.

**Comment by qypengzai** [comment]
> I am using some flutter plugin which are already migrated to androidx, and it makes me migrated my code to androidx also. After then, zego flutter plugin built failed in my project.
> Is there a plan to migrated android sdk to androidx or how can I using flutter sdk when my project already migrated to androidx ?
> 
> refs: https://developer.android.com/jetpack/androidx/migrate

Hello, zegoliveroomplugin 1.0.4 remove all android support because we don't need it. So you can upgrade sdk and try to build your project again.

**Comment by LunaGao** [comment]
@qypengzai  Thanks for your reply. Did this repo upgrade zegoliveroomplugin version to 1.0.4, or I need to upgrade it in my local project?

**Comment by zegodev** [comment]
> @qypengzai Thanks for your reply. Did this repo upgrade zegoliveroomplugin version to 1.0.4, or I need to upgrade it in my local project?

This repo has upgraded to 1.0.4, So you just need to upgeade it in your project by pub or git.

**Comment by qypengzai** [comment]
> @qypengzai Thanks for your reply. Did this repo upgrade zegoliveroomplugin version to 1.0.4, or I need to upgrade it in my local project?

This repo has upgraded to 1.0.4, So you just need to upgrade it in your project by pub or git.Here is the pub address:  https://pub.dev/packages/zegoliveroom_plugin
