### ISSUE TITLE
Need camera permission when I only want to use the audio.

### ISSUE THREAD

**Issue by LunaGao** [zegoim/zego-flutter-sdk#3]
I want only using audio function in my app, and when I follow this repo's example code and https://github.com/zegoim/zego-flutter-sdk/issues/1 , setup my code like this:
```
      ZegoLiveRoomPlugin.setUser(userID, userName);
      ZegoLiveRoomPlugin.loginRoom(roomID, 'test-room-$roomID', ZegoRoomRole.ROOM_ROLE_ANCHOR ).then((result) {

        if(result.errorCode == 0) {
          print('登录房间成功');

          ZegoLiveRoomPublisherPlugin.registerPublisherCallback(
            onPublishStateUpdate: onPublishStateUpdate,
            onPublishQualityUpdate: onPublishQualityUpdate,
          );

          ZegoLiveRoomPublisherPlugin.startPublishing(streamID, 'flutter-example', ZegoPublishFlag.ZEGO_MIX_STREAM);
          ZegoLiveRoomPublisherPlugin.enableMic(true);

          ZegoLiveRoomPlayerPlugin.startPlayingStream(streamID);

          ZegoLiveRoomPlayerPlugin.enableSpeaker(true);

        } else {
          print('登录房间失败，错误码: ${result.errorCode}');
        }
      });
```

But there is a problem which is iOS devices asked camera permission.
I don't want to show up the camera permission requirement.

**Comment by qypengzai** [comment]
Hello, I Think you should call `enableCamera(false)` because the default value of this api is true.If you call this api to disable the camera device, iOS don't asked the camera permission.

**Comment by qypengzai** [comment]
> I want only using audio function in my app, and when I follow this repo's example code and #1 , setup my code like this:
> 
> ```
>       ZegoLiveRoomPlugin.setUser(userID, userName);
>       ZegoLiveRoomPlugin.loginRoom(roomID, 'test-room-$roomID', ZegoRoomRole.ROOM_ROLE_ANCHOR ).then((result) {
> 
>         if(result.errorCode == 0) {
>           print('登录房间成功');
> 
>           ZegoLiveRoomPublisherPlugin.registerPublisherCallback(
>             onPublishStateUpdate: onPublishStateUpdate,
>             onPublishQualityUpdate: onPublishQualityUpdate,
>           );
> 
>           ZegoLiveRoomPublisherPlugin.startPublishing(streamID, 'flutter-example', ZegoPublishFlag.ZEGO_MIX_STREAM);
>           ZegoLiveRoomPublisherPlugin.enableMic(true);
> 
>           ZegoLiveRoomPlayerPlugin.startPlayingStream(streamID);
> 
>           ZegoLiveRoomPlayerPlugin.enableSpeaker(true);
> 
>         } else {
>           print('登录房间失败，错误码: ${result.errorCode}');
>         }
>       });
> ```
> 
> But there is a problem which is iOS devices asked camera permission.
> I don't want to show up the camera permission requirement.

Hello, I Think you should call enableCamera(false) because the default value of this api is true.If you call this api to disable the camera device, iOS don't asked the camera permission.

**Comment by LunaGao** [comment]
Oh, I missing this function. 
It's working now.
Great work! Thank you.
