### ISSUE TITLE
跑demo的时候老出错

### ISSUE THREAD

**Issue by uutan** [zegoim/zego-flutter-sdk#6]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':zegoliveroom_plugin'.
> NDK not configured. 
  Download it with SDK manager.

**Comment by patrick-fu** [comment]
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   A problem occurred configuring project ':zegoliveroom_plugin'.
> 
> > NDK not configured.
> > Download it with SDK manager.

NDK is not configured.

[https://www.jianshu.com/p/abd097da6d6f](https://www.jianshu.com/p/abd097da6d6f)
