### ISSUE TITLE
flutter ZegoLiveRoomPlugin API Reference 链接打不开,或者打开的网页不是api说明

### ISSUE THREAD

**Issue by ntsk13** [zegoim/zego-flutter-sdk#7]
如题,  Flutter ZegoLiveRoomPlugin API Reference 链接打不开,或者打开的网页不是api说明

**Comment by zegodev** [comment]
你好，点进去API Reference之后，点击左边的链接就是API说明

<img width="981" alt="image" src="https://user-images.githubusercontent.com/16834421/71227144-3515d800-2319-11ea-882e-f1ac0d85c745.png">
